version: '3'
services:
  app:
    build: .
    ports:
    - 8000:8000
    depends_on:
    - mysql
    environment:
    - MYSQL_HOST=mysql
    - MYSQL_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD

  mysql:
    image: mysql:8
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=1
    - MYSQL_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD
