version: '3'
services:
  app:
    build: .
    ports:
    - 8000:8000
    depends_on:
    - mysql
    environment:
    - MYSQL_HOST=mysql
    - MYSQL_DATABASE=db
    - MYSQL_USER=app
    - MYSQL_PASSWORD=app

  mysql:
    image: mysql:8
    environment:
    - MYSQL_DATABASE=db
    - MYSQL_USER=app
    - MYSQL_PASSWORD=app
    - MYSQL_RANDOM_ROOT_PASSWORD=1
